version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: node_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres
      DB_PORT: 5433
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "app.js"]
